name: 'todo.hub'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

inputs:
  token:
    description: The GitHub token to use when calling the API
    default: ${{ github.token }}
    required: false

outputs:
  new-issue:
    description: 'URL of created issue'

runs:
  using: node20
  main: dist/index.js
