name: 'todo.hub'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

inputs:
  TOKEN:
    description: The GitHub token to use when calling the API
    default: ${{ github.token }}
    required: false
  MAX_LINE_LENGTH:
    description: Lines of code with more characters will be excluded from TODO-search, since these typically minimized/generated files, which should be ignored (in .todoignore file) anyway
    default: '500'
    required: false

outputs:
  UPDATED_ISSUES:
    description: 'Comma separated list of issue numbers that were update updated during the run.'
  SKIPPED_UNCHANGED_ISSUES:
    description: 'Comma separated list of issue numbers that were not updated because they were already tracked and their state has not changed.'
  ISSUES_FAILED_TO_UPDATE:
    description: 'Comma separated list of issue numbers that failed to updated. Reasons include: permanently deleted issues, PRs that cannot be reopened, because branch was deleted.'
  TODOHUB_CONTROL_ISSUE_ID:
    description: issue number of todoshubs control center
runs:
  using: node20
  main: dist/index.js
