name: Test Local Action

on:
  pull_request:
  push:
    # branches:
    #   - main

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-test
        run: npm run test

  todohub:
    name: Todohub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Run Todohub Action
        id: run-todohub-action
        uses: ./
        with:
          MAX_LINE_LENGTH: '350'
          
      # - name: Test Remote Action
      #   id: test-action
      #   uses: todos-in/todohub@main

      # - name: Print Output
      #   id: output
      #   run: echo "${{ steps.test-action.outputs.new-issue }}"
